// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLRTMcv4ufd2MDvnBaGam1EgiyVWdZ0Q',
    appId: '1:393057938292:web:68099f492610d0cecc9a21',
    messagingSenderId: '393057938292',
    projectId: 'leaderboard-a7253',
    authDomain: 'leaderboard-a7253.firebaseapp.com',
    storageBucket: 'leaderboard-a7253.firebasestorage.app',
    measurementId: 'G-3ZSXEM8ESL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hUPDMtWHTvhjwCCmTsRVQJc3LLEuc90',
    appId: '1:393057938292:android:518201cf1e2558dacc9a21',
    messagingSenderId: '393057938292',
    projectId: 'leaderboard-a7253',
    storageBucket: 'leaderboard-a7253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMFFUSkRI1_LRUMIyfXIenrF-QFHuJaY',
    appId: '1:393057938292:ios:1bfc09eeda19f455cc9a21',
    messagingSenderId: '393057938292',
    projectId: 'leaderboard-a7253',
    storageBucket: 'leaderboard-a7253.firebasestorage.app',
    iosClientId: '393057938292-42lpbvha6vsan5vl1v94bl41r7l4t2b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaderboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMFFUSkRI1_LRUMIyfXIenrF-QFHuJaY',
    appId: '1:393057938292:ios:1bfc09eeda19f455cc9a21',
    messagingSenderId: '393057938292',
    projectId: 'leaderboard-a7253',
    storageBucket: 'leaderboard-a7253.firebasestorage.app',
    iosClientId: '393057938292-42lpbvha6vsan5vl1v94bl41r7l4t2b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaderboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkLRTMcv4ufd2MDvnBaGam1EgiyVWdZ0Q',
    appId: '1:393057938292:web:b5601ea3c33aff27cc9a21',
    messagingSenderId: '393057938292',
    projectId: 'leaderboard-a7253',
    authDomain: 'leaderboard-a7253.firebaseapp.com',
    storageBucket: 'leaderboard-a7253.firebasestorage.app',
    measurementId: 'G-P0CVVJK3CQ',
  );
}
